name = "WAAMTools"
uuid = "f60f9d6b-eca6-4f3f-b21a-faf2f2230c11"
authors = ["Jarrod Angove <jangove@ualberta.ca> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
